name: linkz
description: A web server built using the shelf package.
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  db_annotations:
    path: ./packages/db_annotations/
  authentication:
    path: ./packages/authentication/
  alfred: ^0.1.4+5
  args: ^2.0.0
  envify: ^2.0.0
  jose: ^0.3.2
  logger: ^1.0.0
  shelf: ^1.1.0

dev_dependencies:
  db_query_generator:
    path: ./packages/db_query_generator/
  build_runner: ^2.0.5
  envify_generator: ^2.0.0
  http: ^0.13.3
  test: ^1.17.9
  very_good_analysis: ^2.1.2
