name: db_query_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  db_annotations:
    path: ../db_annotations/
  analyzer: ^1.7.1
  build: ^2.0.2
  source_gen: ^1.0.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
