builders:
  db_query_generator:
    import: "package:db_query_generator/db_query_generator.dart"
    builder_factories: ["dbQueryGenerator"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]